### ISSUE TITLE
better formatting

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe-australia/silverstripe-grouped-cms-menu#47]
I added this to one of my modules:

```scss
.cms-menu__list {
  > .link.children,
  > .current.children {
    > a {
      background-color: #004e7f22;
      &:hover {
        color: #004e7f !important;
        * {
          color: #004e7f !important;
        }
      }
      .menu__icon {
        display: none;
      }
      .text {
        margin-left: 0;
      }
    }
    ul.group {
      margin-left: 0 !important;
      li {
        margin-left: 0 !important;
      }
      .current {
        a {
          font-weight: bold;
        }
      }
    }
  }
  > .current.children {
    background-color: #004e7f;
    color: #fff;
    > a {
      .text,
      .toggle-children {
        font-weight: bold;
        color: #fff;
      }
    }
  }
}

```

![image](https://github.com/symbiote/silverstripe-grouped-cms-menu/assets/167154/3649ae99-af74-479f-b2ca-d77b1731c42c)
