### ISSUE TITLE
Missing Icon on Parent Item

### ISSUE THREAD

**Issue by dcentrica** [silverstripe-australia/silverstripe-grouped-cms-menu#49]
Using SIlverstripe 5.0 and the following config, I cannot for the life of me figure out how to make the icon "take" on the parent nav menu item (well I _will_ find out, but wanted to report it first).

```
SilverStripe\Admin\LeftAndMain:
  menu_groups:
    MyParentMenu:
      icon: 'sitemap'
      children:
        - MyProject-Admin-SomeAdmin
        - MyProject-Admin-OtherAdmin
        - MyProject-Admin-MoreAdmin
``` 

The "sitemap" icon does not show anywhere on the clickable parent "MyParentMenu" menu item.
